
import React from 'react'; // Ensure React is imported for ReactNode types if needed by GIFTS
import { Streamer, Product, Language, UserProfile, MessagePreview, ChatMessage, Person, Order, ChatRoom, UserRole } from './types';
import { Gift, Heart, Star, Sparkles, Zap, Crown, Diamond } from 'lucide-react';

// Theme-matched default images
export const DEFAULT_IMAGES = {
  // Dark grey background with Red text, matching the app theme
  AVATAR: 'https://ui-avatars.com/api/?name=New+User&background=111827&color=dc2626&size=256&bold=true&length=1',
  // Abstract dark geometric/sporty background
  COVER: 'https://images.unsplash.com/photo-1614850523060-8da1d56ae167?w=1200&q=80'
};

export const GIFTS = [
  { id: '1', name: 'Heart', icon: '❤️', price: 10, color: 'red' },
  { id: '2', name: 'Rose', icon: '🌹', price: 50, color: 'pink' },
  { id: '3', name: 'Fire', icon: '🔥', price: 100, color: 'orange' },
  { id: '4', name: 'Party', icon: '🎉', price: 200, color: 'yellow' },
  { id: '5', name: 'Diamond', icon: '💎', price: 500, color: 'blue' },
  { id: '6', name: 'Rocket', icon: '🚀', price: 1000, color: 'purple' },
  { id: '7', name: 'Crown', icon: '👑', price: 5000, color: 'yellow' },
];

export const TRANSLATIONS = {
  en: {
    // Auth
    welcomeBack: 'Welcome Back',
    welcomeDesc: 'Sign in to continue watching and shopping.',
    createAccount: 'Create Account',
    createDesc: 'Join the community of underwear lovers.',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    confirmPassword: 'Confirm Password',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    orContinueWith: 'Or continue with',
    forgotPassword: 'Forgot Password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    loginError: 'Login failed. Please check your credentials.',
    registerError: 'Registration failed. Please try again.',
    registerSuccess: 'Registration successful! Please sign in.',
    // Forgot Password
    resetPasswordTitle: 'Reset Password',
    resetPasswordDesc: 'Enter your email to receive password reset instructions.',
    sendResetLink: 'Send Reset Link',
    backToLogin: 'Back to Login',
    resetLinkSent: 'Password reset link sent! Check your email.',
    resetError: 'Failed to send reset link. Please try again.',
    newPassword: 'New Password',
    updatePassword: 'Update Password',
    passwordUpdated: 'Password updated successfully!',
    setNewPasswordTitle: 'Set New Password',
    setNewPasswordDesc: 'Please enter your new password below.',
    // ... existing translations ...
    menuTitle: 'Menu',
    applyNow: 'Apply Now',
    myOrders: 'My Orders',
    myAddress: 'My Address',
    myPayment: 'My Payment',
    myWallet: 'My Wallet',
    myProducts: 'My Products',
    myGifts: 'My Gifts',
    totalEarnings: 'Total Earnings',
    myRate: 'My Rate',
    myRateTitle: 'My Rate',
    myRateDesc: 'Set your hourly rates for different types of engagement.',
    eventLiveRate: 'Online Event Rate',
    productPresentationRate: 'Product Presentation Rate',
    onsiteEventRate: 'Onsite Event Rate',
    saveRates: 'Save Rates',
    rateSaved: 'Rates saved successfully!',
    perHour: '/ HOUR',
    mySchedule: 'My Schedule',
    logout: 'Log Out',
    home: 'Home',
    discover: 'Discover',
    cart: 'Cart',
    profile: 'Profile',
    people: 'People',
    liveNow: 'Live Now',
    viewAll: 'View All',
    follow: 'FOLLOW',
    followed: 'FOLLOWING',
    pleaseLoginToFollow: 'Please login to follow others.',
    watching: 'watching',
    saySomething: 'Say something...',
    shopItems: 'Shop Items',
    buyNow: 'BUY NOW',
    stock: 'Stock',
    sold: 'Sold',
    remaining: 'Remaining',
    products: 'Products',
    memberSince: 'Member since 2024',
    tags: ['All', 'Hot 🔥', 'New Arrival', 'Sale', 'Briefs', 'Boxers', 'Jockstraps'],
    homeTabs: {
      live: 'Live Stream',
      rooms: 'Rooms',
      models: 'Models'
    },
    // Roles & Upgrade
    roles: {
      model: 'Model',
      organizer: 'Organizer',
      supporter: 'Supporter'
    },
    upgradeTitle: 'Become an Organizer',
    upgradeDesc: 'Unlock exclusive hosting features, manage larger events, and earn more revenue.',
    upgradePrice: '5,000 Coins',
    upgradeButton: 'Upgrade Now',
    insufficientForUpgrade: 'Insufficient coins. Please top up.',
    upgradeSuccess: 'Upgrade Successful! You are now an Organizer.',
    pendingApproval: 'Pending Approval',
    // Model Application
    modelAppTitle: 'Model Application',
    step1Title: 'Close-up Photo',
    step1Desc: 'Please take a clear photo of your face directly looking at the camera.',
    step2Title: 'Half-body Photo',
    step2Desc: 'Please take a photo from your waist up, showing your physique clearly.',
    cameraPermission: 'Camera access is required to take verification photos.',
    retake: 'Retake',
    usePhoto: 'Use Photo',
    submitApp: 'Submit Application',
    takingPhoto: 'Taking photo...',
    instructions: 'Instructions',
    startCamera: 'Open Camera',
    // Organizer Tools
    organizerTools: 'Organizer Tools',
    roomList: 'Room List',
    manageMembers: 'Manage Members',
    banUser: 'Ban User',
    muteUser: 'Mute',
    activeRooms: 'Active Rooms',
    totalMembers: 'Total Members',
    // Wallet Translations
    wallet: 'Wallet',
    currentBalance: 'Current Balance',
    topUp: 'Top Up',
    coins: 'Coins',
    selectAmount: 'Select Amount',
    paymentMethod: 'Payment Method',
    creditDebit: 'Credit / Debit Card',
    truemoney: 'TrueMoney Wallet',
    payNow: 'Pay Now',
    processing: 'Processing...',
    paymentSuccess: 'Payment Successful!',
    exchangeRate: '1 Baht = 1 Coin',
    // Discover Translations
    featured: 'Featured',
    trendingNow: 'Trending Now',
    hotLive: 'Hot Live 🔥',
    recommended: 'Recommended Lives',
    shopCollection: 'Watch Live',
    categories: {
      new: 'New Live',
      sale: 'Flash Sale',
      bundle: 'Big Lot',
      premium: 'Premium'
    },
    // Cart Translations
    myCart: 'My Cart',
    items: 'items',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    total: 'Total',
    checkout: 'CHECKOUT',
    emptyCart: 'Your cart is empty',
    startShopping: 'Start Shopping',
    free: 'Free',
    remove: 'Remove',
    // Profile Translations
    editProfile: 'Edit Profile',
    personalInfo: 'Personal Information',
    physicalStats: 'Physical Stats',
    editGallery: 'Edit Gallery',
    editGalleryTitle: 'Manage Gallery',
    uploadImage: 'Upload Image',
    age: 'Age',
    height: 'Height',
    weight: 'Weight',
    favorites: 'My Preferences',
    gallery: 'My Gallery',
    location: 'Location',
    aboutMe: 'About Me',
    cm: 'cm',
    kg: 'kg',
    years: 'y/o',
    save: 'Save Changes',
    saving: 'Saving...',
    cancel: 'Cancel',
    username: 'Username',
    changeCover: 'Change Cover',
    changeAvatar: 'Change Avatar',
    addTag: 'Add Tag',
    enterTagPlaceholder: 'Ex. Briefs, Jockstrap...',
    followers: 'Followers',
    following: 'Following',
    // Messages
    messages: 'Messages',
    searchMessages: 'Search...',
    noMessages: 'No messages yet',
    typeMessage: 'Type a message...',
    watchLive: 'Watch Live',
    chats: 'Chats',
    groups: 'Groups',
    createRoom: 'Create Room',
    roomName: 'Room Name',
    privacy: 'Privacy',
    public: 'Public',
    private: 'Private',
    create: 'Create',
    members: 'Members',
    // End Live
    endLiveTitle: 'End Live Stream?',
    endLiveDesc: 'Are you sure you want to stop streaming?',
    confirmEnd: 'End Now',
    // Live Selection
    liveSelectionTitle: 'Select Live Type',
    liveSelling: 'Live Selling',
    liveSellingDesc: 'Sell products directly to viewers',
    liveAuction: 'Live Auction',
    liveAuctionDesc: 'Bid and win rare items',
    // My Products
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    productName: 'Product Name',
    price: 'Price',
    description: 'Description',
    colors: 'Colors',
    sizes: 'Sizes',
    deleteConfirm: 'Delete this product?',
    manageStock: 'Manage Stock',
    // Live Product Selection
    selectProductsTitle: 'Select Products for Live',
    noProductsFound: 'No Products Found',
    pleaseAddProduct: 'You need to add products before starting a live sale.',
    goToAddProduct: 'Go to Add Product',
    startLive: 'Start Live',
    selected: 'Selected',
    readyToLive: 'Ready to Live',
    startingIn: 'Starting in',
    // Auction Setup
    auctionSetupTitle: 'Auction Setup',
    duration: 'Duration',
    startingPrice: 'Starting Price',
    startAuction: 'Start Auction',
    min: 'min',
    hour: 'hour',
    hours: 'hours',
    // Auction UI
    currentBid: 'Current Bid',
    topBidder: 'Top Bidder',
    placeBid: 'PLACE BID',
    yourBid: 'Your Bid',
    bidSuccess: 'Bid Placed!',
    bidTooLow: 'Bid too low',
    // Address & Payment
    addNewAddress: 'Add New Address',
    recipientName: 'Recipient Name',
    phoneNumber: 'Phone Number',
    addressDetails: 'Address Details',
    province: 'Province',
    postalCode: 'Postal Code',
    defaultAddress: 'Default',
    addNewPayment: 'Add Payment Method',
    cardNumber: 'Card Number',
    cardHolder: 'Card Holder Name',
    expiryDate: 'Expiry Date',
    cvv: 'CVV',
    linked: 'Linked',
    delete: 'Delete',
    // My Orders
    orderId: 'Order ID',
    orderDate: 'Date',
    orderTotal: 'Order Total',
    trackOrder: 'Track Order',
    writeReview: 'Write Review',
    buyAgain: 'Buy Again',
    status: {
      all: 'All',
      pending: 'To Pay',
      shipping: 'To Ship',
      delivered: 'Completed',
      cancelled: 'Cancelled'
    },
    trackingTitle: 'Delivery Status',
    trackingNumber: 'Tracking Number',
    copy: 'Copy',
    copied: 'Copied',
  },
  th: {
    // Auth
    welcomeBack: 'ยินดีต้อนรับกลับ',
    welcomeDesc: 'เข้าสู่ระบบเพื่อรับชมไลฟ์และช้อปปิ้ง',
    createAccount: 'สร้างบัญชีผู้ใช้',
    createDesc: 'เข้าร่วมคอมมูนิตี้คนรักกางเกงในชาย',
    email: 'อีเมล',
    password: 'รหัสผ่าน',
    fullName: 'ชื่อ-นามสกุล',
    confirmPassword: 'ยืนยันรหัสผ่าน',
    signIn: 'เข้าสู่ระบบ',
    signUp: 'สมัครสมาชิก',
    orContinueWith: 'หรือเข้าสู่ระบบด้วย',
    forgotPassword: 'ลืมรหัสผ่าน?',
    dontHaveAccount: "ยังไม่มีบัญชีใช่ไหม?",
    alreadyHaveAccount: "มีบัญชีอยู่แล้ว?",
    loginError: 'เข้าสู่ระบบไม่สำเร็จ โปรดตรวจสอบข้อมูล',
    registerError: 'สมัครสมาชิกไม่สำเร็จ โปรดลองใหม่',
    registerSuccess: 'สมัครสมาชิกสำเร็จ! กรุณาเข้าสู่ระบบ',
    // Forgot Password
    resetPasswordTitle: 'รีเซ็ตรหัสผ่าน',
    resetPasswordDesc: 'กรอกอีเมลของคุณเพื่อรับลิงก์ตั้งรหัสผ่านใหม่',
    sendResetLink: 'ส่งลิงก์รีเซ็ต',
    backToLogin: 'กลับไปหน้าเข้าสู่ระบบ',
    resetLinkSent: 'ส่งลิงก์รีเซ็ตเรียบร้อย! โปรดตรวจสอบอีเมล',
    resetError: 'ไม่สามารถส่งลิงก์ได้ โปรดลองอีกครั้ง',
    newPassword: 'รหัสผ่านใหม่',
    updatePassword: 'อัปเดตรหัสผ่าน',
    passwordUpdated: 'เปลี่ยนรหัสผ่านเรียบร้อยแล้ว!',
    setNewPasswordTitle: 'ตั้งรหัสผ่านใหม่',
    setNewPasswordDesc: 'กรุณากรอกรหัสผ่านใหม่ของคุณด้านล่าง',
    // ... existing translations ...
    menuTitle: 'เมนู',
    applyNow: 'สมัครเลย',
    myOrders: 'รายการคำสั่งซื้อ',
    myAddress: 'ที่อยู่ของฉัน',
    myPayment: 'ช่องทางการชำระเงิน',
    myWallet: 'กระเป๋าเงิน',
    myProducts: 'สินค้าของฉัน',
    myGifts: 'ของขวัญที่ได้รับ',
    totalEarnings: 'รายได้รวมทั้งหมด',
    myRate: 'เรทค่าตัว',
    myRateTitle: 'เรทค่าตัว',
    myRateDesc: 'ตั้งค่าเรทราคาของคุณสำหรับงานประเภทต่างๆ',
    eventLiveRate: 'ค่าตัว Online Event',
    productPresentationRate: 'ค่าตัว นำเสนอสินค้า',
    onsiteEventRate: 'ค่าตัว Onsite Event',
    saveRates: 'บันทึกเรทราคา',
    rateSaved: 'บันทึกเรียบร้อยแล้ว!',
    perHour: '/ ชั่วโมง',
    mySchedule: 'ตารางงานของฉัน',
    logout: 'ออกจากระบบ',
    home: 'หน้าหลัก',
    discover: 'ค้นพบ',
    cart: 'รถเข็น',
    profile: 'โปรไฟล์',
    people: 'ผู้คน',
    liveNow: 'ไลฟ์สด',
    viewAll: 'ดูทั้งหมด',
    follow: 'ติดตาม',
    followed: 'ติดตามแล้ว',
    pleaseLoginToFollow: 'กรุณาเข้าสู่ระบบเพื่อติดตาม',
    watching: 'คนดู',
    saySomething: 'พูดคุย...',
    shopItems: 'สินค้าในร้าน',
    buyNow: 'ซื้อเลย',
    stock: 'คงเหลือ',
    sold: 'ขายแล้ว',
    remaining: 'เหลือ',
    products: 'สินค้า',
    memberSince: 'สมาชิกตั้งแต่ 2024',
    tags: ['ทั้งหมด', 'มาแรง 🔥', 'สินค้าใหม่', 'ลดราคา', 'กางเกงใน', 'บ็อกเซอร์', 'จ็อกสแตรป'],
    homeTabs: {
      live: 'Live สด',
      rooms: 'ห้อง',
      models: 'นายแบบ'
    },
    // Roles & Upgrade
    roles: {
      model: 'นายแบบ',
      organizer: 'ผู้จัด',
      supporter: 'ผู้สนับสนุน'
    },
    upgradeTitle: 'สมัครเป็นผู้จัด (Organizer)',
    upgradeDesc: 'ปลดล็อกฟีเจอร์การไลฟ์ขั้นสูง จัดการอีเวนต์ และสร้างรายได้ที่มากขึ้น',
    upgradePrice: '5,000 เหรียญ',
    upgradeButton: 'อัปเกรดทันที',
    insufficientForUpgrade: 'เหรียญไม่พอ กรุณาเติมเงิน',
    upgradeSuccess: 'อัปเกรดสำเร็จ! คุณเป็นผู้จัดแล้ว',
    pendingApproval: 'รออนุมัติ',
    // Model Application
    modelAppTitle: 'สมัครเป็นนายแบบ',
    step1Title: 'รูปถ่ายหน้าตรง',
    step1Desc: 'กรุณาถ่ายรูปหน้าตรง (ซูมใบหน้า) ให้เห็นใบหน้าชัดเจน',
    step2Title: 'รูปถ่ายครึ่งตัว',
    step2Desc: 'กรุณาถ่ายรูปครึ่งตัวบน ให้เห็นรูปร่างชัดเจน',
    cameraPermission: 'จำเป็นต้องใช้กล้องเพื่อถ่ายรูปยืนยันตัวตน',
    retake: 'ถ่ายใหม่',
    usePhoto: 'ใช้รูปนี้',
    submitApp: 'ส่งใบสมัคร',
    takingPhoto: 'กำลังถ่าย...',
    instructions: 'คำแนะนำ',
    startCamera: 'เปิดกล้อง',
    // Organizer Tools
    organizerTools: 'เครื่องมือผู้จัด',
    roomList: 'รายชื่อ Room',
    manageMembers: 'จัดการสมาชิก',
    banUser: 'แบนผู้ใช้',
    muteUser: 'ปิดเสียง',
    activeRooms: 'ห้องที่ใช้งานอยู่',
    totalMembers: 'สมาชิกทั้งหมด',
    // Wallet Translations
    wallet: 'กระเป๋าเงิน',
    currentBalance: 'ยอดเงินคงเหลือ',
    topUp: 'เติมเงิน',
    coins: 'เหรียญ',
    selectAmount: 'เลือกจำนวน',
    paymentMethod: 'ช่องทางชำระเงิน',
    creditDebit: 'บัตรเครดิต / เดบิต',
    truemoney: 'ทรูมันนี่ วอลเล็ท',
    payNow: 'ชำระเงิน',
    processing: 'กำลังดำเนินการ...',
    paymentSuccess: 'ชำระเงินสำเร็จ!',
    exchangeRate: '1 บาท = 1 เหรียญ',
    // Discover Translations
    featured: 'แนะนำ',
    trendingNow: 'กำลังมาแรง',
    hotLive: 'ไลฟ์ยอดฮิต 🔥',
    recommended: 'ไลฟ์แนะนำ',
    shopCollection: 'ชมไลฟ์',
    categories: {
      new: 'ไลฟ์ใหม่',
      sale: 'ลดกระหน่ำ',
      bundle: 'เหมาโหล',
      premium: 'พรีเมียม'
    },
    // Cart Translations
    myCart: 'รถเข็นของฉัน',
    items: 'รายการ',
    subtotal: 'ยอดรวมสินค้า',
    shipping: 'ค่าจัดส่ง',
    total: 'ยอดรวมทั้งสิ้น',
    checkout: 'ชำระเงิน',
    emptyCart: 'ไม่มีสินค้าในรถเข็น',
    startShopping: 'เริ่มช้อปปิ้ง',
    free: 'ฟรี',
    remove: 'ลบ',
    // Profile Translations
    editProfile: 'แก้ไขโปรไฟล์',
    personalInfo: 'ข้อมูลส่วนตัว',
    physicalStats: 'สัดส่วนร่างกาย',
    editGallery: 'แก้ไขแกลเลอรี่',
    editGalleryTitle: 'จัดการแกลเลอรี่',
    uploadImage: 'อัปโหลดรูปภาพ',
    age: 'อายุ',
    height: 'ส่วนสูง',
    weight: 'น้ำหนัก',
    favorites: 'ความชอบ',
    gallery: 'แกลเลอรี่ของฉัน',
    location: 'ที่อยู่',
    aboutMe: 'เกี่ยวกับฉัน',
    cm: 'ซม.',
    kg: 'กก.',
    years: 'ปี',
    save: 'บันทึกการแก้ไข',
    saving: 'กำลังบันทึก...',
    cancel: 'ยกเลิก',
    username: 'ชื่อผู้ใช้',
    changeCover: 'เปลี่ยนรูปปก',
    changeAvatar: 'เปลี่ยนรูปโปรไฟล์',
    addTag: 'เพิ่มแท็ก',
    enterTagPlaceholder: 'เช่น บ็อกเซอร์, จ็อกสแตรป...',
    followers: 'ผู้ติดตาม',
    following: 'กำลังติดตาม',
    // Messages
    messages: 'ข้อความ',
    searchMessages: 'ค้นหา...',
    noMessages: 'ไม่มีข้อความ',
    typeMessage: 'พิมพ์ข้อความ...',
    watchLive: 'ดูไลฟ์',
    chats: 'แชท',
    groups: 'กลุ่ม',
    createRoom: 'สร้างห้อง',
    roomName: 'ชื่อห้องแชท',
    privacy: 'ความเป็นส่วนตัว',
    public: 'สาธารณะ',
    private: 'ส่วนตัว',
    create: 'สร้าง',
    members: 'สมาชิก',
    // End Live
    endLiveTitle: 'จบการไลฟ์?',
    endLiveDesc: 'คุณแน่ใจหรือไม่ว่าต้องการหยุดการถ่ายทอดสด?',
    confirmEnd: 'จบตอนนี้',
    // Live Selection
    liveSelectionTitle: 'เลือกประเภทการไลฟ์',
    liveSelling: 'ไลฟ์ขายของ',
    liveSellingDesc: 'ขายสินค้าให้กับผู้ชมโดยตรง',
    liveAuction: 'ไลฟ์ประมูล',
    liveAuctionDesc: 'ประมูลสินค้าแรร์ไอเทม',
    // My Products
    addProduct: 'เพิ่มสินค้า',
    editProduct: 'แก้ไขสินค้า',
    productName: 'ชื่อสินค้า',
    price: 'ราคา',
    description: 'รายละเอียด',
    colors: 'สี',
    sizes: 'ไซส์',
    deleteConfirm: 'ต้องการลบสินค้านี้ใช่ไหม?',
    manageStock: 'จัดการสต็อก',
    // Live Product Selection
    selectProductsTitle: 'เลือกสินค้าสำหรับไลฟ์',
    noProductsFound: 'ไม่พบสินค้า',
    pleaseAddProduct: 'คุณต้องเพิ่มสินค้าก่อนเริ่มไลฟ์ขายของ',
    goToAddProduct: 'ไปที่เพิ่มสินค้า',
    startLive: 'เริ่มไลฟ์',
    selected: 'เลือกแล้ว',
    readyToLive: 'เตรียมพร้อมไลฟ์',
    startingIn: 'เริ่มใน',
    // Auction Setup
    auctionSetupTitle: 'ตั้งค่าการประมูล',
    duration: 'ระยะเวลา',
    startingPrice: 'ราคาเริ่มต้น',
    startAuction: 'เริ่มประมูล',
    min: 'นาที',
    hour: 'ชั่วโมง',
    hours: 'ชั่วโมง',
    // Auction UI
    currentBid: 'ราคาปัจจุบัน',
    topBidder: 'ผู้ประมูลสูงสุด',
    placeBid: 'เสนอราคา',
    yourBid: 'ราคาของคุณ',
    bidSuccess: 'เสนอราคาสำเร็จ!',
    bidTooLow: 'ราคาต่ำเกินไป',
    // Address & Payment
    addNewAddress: 'เพิ่มที่อยู่ใหม่',
    recipientName: 'ชื่อผู้รับ',
    phoneNumber: 'เบอร์โทรศัพท์',
    addressDetails: 'รายละเอียดที่อยู่',
    province: 'จังหวัด',
    postalCode: 'รหัสไปรษณีย์',
    defaultAddress: 'ค่าเริ่มต้น',
    addNewPayment: 'เพิ่มช่องทางชำระเงิน',
    cardNumber: 'หมายเลขบัตร',
    cardHolder: 'ชื่อผู้ถือบัตร',
    expiryDate: 'วันหมดอายุ',
    cvv: 'CVV',
    linked: 'เชื่อมต่อแล้ว',
    delete: 'ลบ',
    // My Orders
    orderId: 'หมายเลขคำสั่งซื้อ',
    orderDate: 'วันที่สั่งซื้อ',
    orderTotal: 'ยอดรวม',
    trackOrder: 'ติดตามพัสดุ',
    writeReview: 'เขียนรีวิว',
    buyAgain: 'ซื้อซ้ำ',
    status: {
      all: 'ทั้งหมด',
      pending: 'ที่ต้องชำระ',
      shipping: 'ที่ต้องจัดส่ง',
      delivered: 'สำเร็จ',
      cancelled: 'ยกเลิก'
    },
    trackingTitle: 'สถานะการจัดส่ง',
    trackingNumber: 'เลขพัสดุ',
    copy: 'คัดลอก',
    copied: 'คัดลอกแล้ว',
  }
};

export const MOCK_USER_PROFILE: UserProfile = {
  username: 'New User',
  avatar: DEFAULT_IMAGES.AVATAR,
  coverImage: DEFAULT_IMAGES.COVER,
  role: 'supporter',
  modelApplicationStatus: 'none',
  age: 0,
  height: 0,
  weight: 0,
  location: '',
  bio: '',
  favorites: [],
  gallery: [],
  followers: 0,
  following: 0,
};

export const DISCOVER_TAGS = [
  '#Sexy', '#GymWear', '#Cotton100%', '#LimitedEdition', '#ThaiBrand', '#ModelLive'
];

export const MOCK_PEOPLE: Person[] = [
  { id: '1', username: 'Alex', avatar: 'https://ui-avatars.com/api/?name=Alex&background=random', isOnline: true, followers: 1200, role: 'model' },
  { id: '2', username: 'Mike', avatar: 'https://ui-avatars.com/api/?name=Mike&background=random', isOnline: false, followers: 450, role: 'supporter' },
  { id: '3', username: 'Sarah', avatar: 'https://ui-avatars.com/api/?name=Sarah&background=random', isOnline: true, followers: 8900, role: 'organizer' },
  { id: '4', username: 'John', avatar: 'https://ui-avatars.com/api/?name=John&background=random', isOnline: false, followers: 120, role: 'supporter' },
  { id: '5', username: 'David', avatar: 'https://ui-avatars.com/api/?name=David&background=random', isOnline: true, followers: 3400, role: 'model' },
  { id: '6', username: 'Chris', avatar: 'https://ui-avatars.com/api/?name=Chris&background=random', isOnline: true, followers: 560, role: 'supporter' },
  { id: '7', username: 'Tom', avatar: 'https://ui-avatars.com/api/?name=Tom&background=random', isOnline: false, followers: 230, role: 'model' },
  { id: '8', username: 'Ben', avatar: 'https://ui-avatars.com/api/?name=Ben&background=random', isOnline: true, followers: 89, role: 'supporter' },
];
